#!/usr/bin/env bash
docker run \
    --name zigbee2mqtt_garage \
    --restart=unless-stopped \
    -p 8081:8081 \
    -v /Users/glandix/zigbee2mqtt_garage/data:/app/data \
    -v /run/udev:/run/udev:ro \
    -e TZ=America/Chicago \
	-d \
    koenkk/zigbee2mqtt
