#!/usr/bin/env bash
docker run \
    --name z2m_garage \
    --restart=unless-stopped \
    -p 8082:8080 \
    -v ./data:/app/data \
    -v /run/udev:/run/udev:ro \
    -e TZ=America/Chicago \
	-d \
    koenkk/zigbee2mqtt
